#ifndef __SINTAX_ERRORS_CODE_H_
#define __SINTAX_ERRORS_CODE_H_

#define ERROR_REQUEST_MAX_LENGHT		 		0001
#define ERROR_MAL_FORMATED_MSGPCK 		0002
#define ERROR_TOKEN_MISSING 			0003
#define ERROR_TOKEN_NOT_MATCH 			0004
#define ERROR_REQUEST_MISSING_STX 		0005

#define ERROR_UNKNOW					9999
#define ERROR_MSGPACK_UNKNOW			9998
#define ERROR_32BIT_PROCESSING			9001
#define ERROR_MSGPACK_PROCESSING		9002

#define ERROR_MISSING_COMMAND_BYTE		0105
#define ERROR_COMMAND_NOT_FOUND			0106
#define ERROR_COMMAND_MISSING_ARGS_PACK	0107
#define ERROR_COMMAND_ARGS_INVALID		0108
#define ERROR_COMMAND_ARGS_NOT_FOUND	0109
#define ERROR_COMMAND_ARGS_MISSING		0109
#define ERROR_COMMAND_ARGS_TOO_MANY		0110

#endif
