#ifndef __SINTAX_ERRORS_CODE_H_
#define __SINTAX_ERRORS_CODE_H_

#define REQUEST_MAX_LENGHT_ERROR 		0001
#define MAL_FORMATED_MSGPCK_ERROR 		0002
#define TOKEN_MISSING_ERROR 			0003
#define TOKEN_NOT_MATCH_ERROR 			0004

#define UNKNOW_ERROR					9999

#define MISSING_COMMAND_BYTE_ERROR		0105
#define COMMAND_NOT_FOUND_ERROR			0106
#define COMMAND_MISSING_ARGS_PACK_ERROR	0107
#define COMMAND_ARGS_INVALID_ERROR		0108
#define COMMAND_ARGS_NOT_FOUND_ERROR	0109
#define COMMAND_ARGS_MISSING_ERROR		0109
#define COMMAND_ARGS_TOO_MANY_ERROR		0110

#endif
