#ifndef __SINTAX_ERRORS_CODE_H_
#define __SINTAX_ERRORS_CODE_H_

#define ERROR_NONE						0
#define ERROR_REQUEST_MAX_LENGHT		1
#define ERROR_REQUEST_MISSING_STX 		2
#define ERROR_REQUEST_MISSING_STX 		2
#define ERROR_INIT_MSGPACK				3


#define ERROR_MAL_FORMED_REQUEST 		10
#define ERROR_MAL_FORMED_MSGPCK 		11
#define ERROR_TOKEN_MISSING 			12
#define ERROR_TOKEN_NOT_MATCH 			13


#define ERROR_UNKNOW					9999
#define ERROR_MSGPACK_UNKNOW			9998
#define ERROR_MSGPACK_UNKNOW_TYPE		9997
#define ERROR_MSGPACK_UNIMPLEMENTED		9996
#define ERROR_MSGPACK_4BCP_UNKNOW		9995
#define ERROR_MSGPACK_4BCP_ELEMENT_HAS_NO_KEY 		9994
#define ERROR_MSGPACK_4BCP_ELEMENT_PROCESSING 		9993
#define ERROR_MSGPACK_4BCP_ELEMENT_KEY_PROCESSING 	9992
#define ERROR_MSGPACK_4BCP_NO_COMMAND_FLAG 			9991
#define ERROR_MSGPACK_4BCP_NESTED_ELEMENTS_OUT_OF_BOUNDS 9990
#define ERROR_MSGPACK_4BCP_MAP_ZERO_ELEMENTS		9989



#define ERROR_32BIT_PROCESSING			9001
#define ERROR_32BIT_RESETING			9002
#define ERROR_MSGPACK_PROCESSING		9010
#define ERROR_MSGPACK_NOT_IN_FINISHED_STATE 9020


#define ERROR_MISSING_COMMAND_BYTE		105
#define ERROR_COMMAND_NOT_FOUND			106
#define ERROR_COMMAND_MISSING_ARGS_PACK	107
#define ERROR_COMMAND_ARGS_INVALID		108
#define ERROR_COMMAND_ARGS_NOT_FOUND	109
#define ERROR_COMMAND_ARGS_MISSING		109
#define ERROR_COMMAND_ARGS_TOO_MANY		110
#define ERROR_COMMAND_EXECUTION_FAILED	111

#define ERROR_MSGPACK_4BCP_WORD_NOT_MAPPED	301
#define ERROR_MSGPACK_4BCP_WORD_EXPECTED	302
#define ERROR_MSGPACK_4BCP_WORD_MISSING		303
#define ERROR_MSGPACK_4BCP_PROCESSING_FLOW	304
#define ERROR_MSGPACK_4BCP_IN_FINISHED_STATE_WITH_REMAINING_BYTES 305
#define ERROR_MSGPACK_4BCP_UNKNOW_COMMAND 	305
#define ERROR_MSGPACK_4BCP_EXECUTE_FLAG 	306

#endif
